version: "3"
services:
  email:
    container_name: email
    build:
      context: .
      args:
        - APP=email
    ports:
      - "4444:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  github-stack:
    container_name: github-stack
    build:
      context: .
      args:
        - APP=github-stack
    restart: always
    ports:
      - "4445:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass123
